# Generated by Django 5.2.4 on 2025-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='Details',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
