# Generated by Django 5.2.4 on 2025-09-13 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tips_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('Amount', models.IntegerField()),
                ('Details', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_table')),
            ],
        ),
        migrations.DeleteModel(
            name='Remainder',
        ),
    ]
