# Generated by Django 5.2.4 on 2025-10-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='set_date',
        ),
    ]
