# Generated by Django 5.2.4 on 2025-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
