# Generated by Django 5.2.4 on 2025-11-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='Status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
